# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Get latest Pester version
      run: Install-Module Pester -Force -Verbose -Confirm:$false
      
    - name: Run Line Unit tests
      run: |
          cd .\Source\UnitTests
          using module ..\Classes\World.psm1
          using module ..\Classes\Console.psm1
          using module ..\Classes\Cursor.psm1
          using module ..\Classes\UI.psm1
          using module ..\Classes\Line.psm1
          
          .\Source\UnitTests\line_units.ps1

    # Runs a set of commands using the runners shell
    #- name: Run a multi-line script
    #  run: |
    #    echo Add other actions to build,
    #    echo test, and deploy your project.
