# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Pester
        run: Install-Module Pester -Force -Verbose -Confirm:$false

      - name: Line Unit tests
        run: .\Source\UnitTests\line_units.ps1

      - name: World Unit tests
        run: .\Source\UnitTests\world_units.ps1
      # Console Units are excluded from CI/CD
      #- name: Console Unit tests
      #  run: .\Source\UnitTests\console_units.ps1
